---
title: "ILDP2: pilot"
output: html_document
---

## Prepare the workspace for analysis:
```{r, echo = F}

rm(list=ls())
library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

range01 <- function(x){(x-min(x))/(max(x)-min(x))} # function that scales at {0;1}:
```


## Load and assess the data
 (trial - trial number; block - block number; stim - face type [1 or 2]; shock - "shock administered ?"; gsr - galvanic skin response; subject - subject number)
```{r, echo = T}
load('/Users/alebedev/GitHub/ILDP2_pilot/data/rdata.rda')
head(rdata)
```

## Emulate some artificial data based on subject 1
```{r, echo = F}
rdata$gsr <- range01(rdata$gsr)

rdata <- rbind(rdata,rdata,rdata,rdata,rdata,rdata,rdata,rdata,rdata,rdata)
rdata$subject <- c(rep(1,max(rdata$trial)),
                   rep(2,max(rdata$trial)),
                   rep(3,max(rdata$trial)),
                   rep(4,max(rdata$trial)),
                   rep(5,max(rdata$trial)),
                   rep(6,max(rdata$trial)),
                   rep(7,max(rdata$trial)),
                   rep(8,max(rdata$trial)),
                   rep(9,max(rdata$trial)),
                   rep(10,max(rdata$trial)))
rdata$gsr <- rdata$gsr+sqrt(rnorm(800,0,0.5)^2)
```


## Reorganize the data:
```{r, echo = F}
subjList <- unique(rdata[,'subject'])  # list of subjects x blocks
numSubjs <- length(subjList)  # number of subjects
maxTrials <- max(rdata$trial)


Tsubj <- as.vector(rep(0, numSubjs))
response <- array(0, c(numSubjs, maxTrials) )
stimulus <- array(0, c(numSubjs, maxTrials) )
shock <- array(0, c(numSubjs, maxTrials) )


for (i in 1:numSubjs) {
  curSubj      <- subjList[i]
  Tsubj[i] <- sum(rdata$subject == curSubj)  # Tsubj[N]
  useTrials    <- Tsubj[i]
  tmp          <- subset(rdata, rdata$subject == curSubj)
  response[i, 1:useTrials]   <- tmp$gsr
  stimulus[i, 1:useTrials]   <- tmp$stim
  shock[i, 1:useTrials]   <- tmp$shock
}


dataList <- list(
  N             = numSubjs,
  T             = maxTrials,
  response      = response,
  stimulus      = stimulus,
  shock         = shock,
  Tsubj         = Tsubj
)
```

## Run the model
```{r, echo = F}
# Set sampler parameters
adapt_delta   = 0.99
stepsize      = 1
max_treedepth = 10
nchain        = 4
nthin         = 1
niter         = 2000
nwarmup       = 1000
nthin         = 1

### Run Model:
myfit <- stan(file    = "/Users/alebedev/GitHub/ILDP2_pilot/stan_models/bandit2arm_instr.stan",
              data    = dataList, 
              #                  pars    = parameters,
              warmup  = nwarmup,
              #                  init    = genInitList, 
              iter    = niter, 
              chains  = nchain,
              thin    = nthin,
              control = list(adapt_delta   = adapt_delta, 
                             max_treedepth = max_treedepth, 
                             stepsize      = stepsize) )
```

